#!/usr/bin/env bash

export PATH="/sbin:${PATH}"
export PATH="/usr/sbin:${PATH}"
export PATH="$(brew --prefix)/sbin:${PATH}"
export PATH="/bin:${PATH}"
export PATH="/usr/bin:${PATH}"
export PATH="/usr/local/bin:${PATH}"
export PATH="$(brew --prefix)/bin:${PATH}"
export PATH="${DEVTOOLS_DIR}/emacs/nextstep/Emacs.app/Contents/MacOS:${PATH}"
export PATH="${DEVTOOLS_DIR}/emacs/nextstep/Emacs.app/Contents/MacOS/bin:${PATH}"
export PATH="${EMACSDIR}/bin:${PATH}"
export PATH="$(brew --prefix)/opt/make/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gnu-getopt/bin:${PATH}"
export PATH="$(brew --prefix)/opt/grep/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gnu-tar/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/findutils/libexec/gnubin:${PATH}"
export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"
